### PR TITLE
Less native

### PR DESCRIPTION
**Pull request by zwilias**
Staying true to our tagline: "the least amount of native possible!"

### CODE REVIEW

**Comment by BrianHicks** [comment]
Here's the plan: I'm gonna figure out how to upgrade elm-test on master. Then can you rebase this against latest master so we only do one thing at once?

**Comment by BrianHicks** [comment]
I'm starting to see why you did what you did with the Makefile, by the way 💇‍♂️

**Comment by BrianHicks** [comment]
I tried this again after your merge and it looks like the examples build now. Hooray!

So thanks a lot, and I'm going to merge it now. This does require a major version bump, so I'm not going to release it right away (there are a couple more things I'm planning to work on over the next couple weeks that I want to go in the next major version to make the upgrade worth it.)

**Comment by zwilias** [comment]
❤️

**Pull request merged**
