### PR TITLE
Massive Refactor for Better Types

### LINKED ISSUE #3: Create series
We can compare two implementations of the same function, next it would be helpful to compare a series of inputs to the same function. Something like this:

```elm
length : Benchmark
length =
    List.range 0 6
        |> List.map (flip (^) 10 >> List.range 1)
        |> Benchmark.series1 "length" List.length
```

Where `Benchmark.series1` looks like `series : String -> (a -> b) -> List a -> Benchmark`. This would go through `series8`, with the last argument always being the list.

Names are a problem to manage here. In the example above I'd like to see "length (1)" through "length (1000000)" instead of "length ([1])" through "length ([1,2 .. 1000000])" (with all million values actually in there.)

The other problem is that we'll inevitably want to create series at other argument positions, with no good way to do it… we don't want to `flip`, it may introduce additional overhead (but now that I'm saying this, we *do* have a way to test…)

### LINKED ISSUE #21: Support for comparing 3 benchmarks (up from 2)
Today one can compare 2 benchmarks against each other. This is great when one want's to compare old code (TM) to new code (TM) and see if you're actually making things better or not.

Once in a while though, it makes sense to compare up to three different things at the same time, which elm-benchmark does not support.

Let's say I'm working on a new data-structure. It makes sense to compare to a similar data-structure, to justify why a new data-structure is needed, but it might also make sense to compare to another implementation. OR it makes sense to compare against another data-structure, as well as old code (TM) and new code (TM). Or perhaps you've found three implementations for a thing, and you want to check which one is better for your use case.

tl; dr;
Allowing the comparison of three benchmarks, allows one to compare new code against previous code, as well as against a base line.

I can also see the use case for comparing 4 benchmarks as well, but that is a very narrow use case of comparing three data-structures for one use case. I think todays comparison of two benchmarks supports 85% of all use cases, 3 comparisons 14%, and 4 would be a whopping 1%. At least for me.

### LINKED ISSUE #23: Improve Benchmark data structure
## Current state

This is the current data structure used to organise benchmarks:

``` elm
type Benchmark
    = Benchmark String Operation Status
    | Group String (List Benchmark)
    | Compare String Benchmark Benchmark
```

It is simple and concise, however it allows for nonsensical benchmark structures. Do we want to be able to compare a `Group` with a single `Benchmark`? Or compare two comparisons?

When some of these awkward benchmark structures are used we get the following message:

> Sorry, I can't compare these kinds of benchmarks directly.
> Here are the serialized values so you can do it yourself:

It is nice to get some results back, so the user can make sense of it as they please. But it seems like no one would rely on such a feature (I would love to hear an example where this is useful!).

## 1st suggestion

My suggestion is to use a data structure that disallows possible unwanted states. I have identified the following features that are wanted from the data structure:

- Named simple or comparison benchmarks (possibly more than 2 benchmarks in a comparison in the future)
- A way to organise the benchmarks in named groups.

The following data structure gives such features while disallowing the unwanted states:

``` elm
type Benchmark
    = Benchmark String Operation Status


type BenchmarkTree
    = Simple Benchmark
    | Compare String Benchmark Benchmark
    | Group String (List BenchmarkTree)
```

I believe this is better, but I would like to go even further.

## 2nd suggestion

I don't think a `Group` should hold a mix of subgroups and `Simple`/`Compare` benchmarks. If we disallow such a mix it opens up the possibility for other ways of rendering the benchmark results. Benchmarks from the same group can be presented as belonging together (on a table, a chart or anything else).

I have in mind using bar charts to show results from a given group of benchmarks where it makes sense to put results on the same graph side by side. The idea of using charts was already mentioned in #4. Comparisons can be grouped together on the bar chart. Confidence intervals can be used to show the standard deviation of the benchmarks. Hints can be used to reveal even more information such as **total runtime** and **sampling**.

Something like this but nicer (using elm-plot):

bar charts

This is a data structure that separates the grouping structure from the benchmarks in order to disallow mixing groups and benchmarks:

``` elm
type Benchmark
    = Benchmark String Operation Status


type BenchmarkEntity
    = Simple Benchmark
    | Compare String Benchmark Benchmark


type BenchmarkTree
   = Group String (List BenchmarkEntity)
   | Tree String (List BenchmarkTree)
```

## Implementation

I would love to write a PR to update `elm-benchmark` with this new data structure (or a modified version of it if preferred). I do realise this is a major change and may be unwanted. However if it is something of interest, maybe it should come with version `2.0.0` when Elm `0.19` is released.

I have opened this issue to gather feedback on such a change and whether or not I should spend the time writing a PR for it. :smile:

### PR DESCRIPTION
**Pull request by BrianHicks**
Changes almost everything in the library.

Benchmarks are now a first-class citizen in LowLevel, instead of Operations. The sampling code has moved to LowLevel too. This has had some fun effects elsewhere, like:

- We can now have series as well as single benchmarks (the types line up better)
- We don't need `benchmark1` through `benchmark8`, thunks are just as fast (and we're going for consistency over absolute speed when measuring, so it would've been OK if they were anyway.)
- I had to rip out the comparison code in the runner. (😢) I'm going to redesign the runner though, so this is OK. We won't release like this.

Docs are awful, but this is only gonna get bigger so I'm going to call it good here and recognize it won't get released in this state.

Fixes #3 
Fixes #21 
Fixes #23 

And since I know that's gonna send notifications far and wide: I'm planning on merging later this week. @zwilias, @Skinney, and @basile-henry: you're welcome to leave a review and I would appreciate it, but don't feel obligated to do so. 😄

### CODE REVIEW

**Comment by BrianHicks** [comment]
note to self: squash these commits when merging. They're broken in a bunch of places and will make bisecting harder in the future if it's ever necessary.

**Comment by robinheghan** [comment]
I've only had a brief time to review this, but I'd say things are looking good! I don't have anything against the `name` function. What is it that you think is bad about it?

**Comment by BrianHicks** [comment]
I just don't like exposing getter/setter functions in general. This one feels sufficiently justified (because it helps hide `Operation` and completely prevent exposing it) so maybe I should remove the TODO.

**Comment by BrianHicks** [comment]
@Skinney I'm also interested in your take on the new `compare` signature. If you have time to look, usage is in `examples/ElmArrayExploration.elm`

**Comment by robinheghan** [comment]
I think it looks great! I also like the new signature for `benchmark`. Simpler overall =)

**Pull request merged**
